name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  xcodebuild-latest:
    name: xcodebuild (16.2)
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[ci skip xcodebuild-latest]')
    runs-on: macos-15
    strategy:
      matrix:
        command: [test, '']
        platform: [iOS, macOS, macCatalyst, tvOS, visionOS, watchOS]
    steps:
      - uses: actions/checkout@v4
      - name: Debug ${{ matrix.platform }}
        uses: capturecontext/swift-package-action@2.0
        with:
          workspace: Package.xcworkspace
          cache-derived-data: true
          command: xcodebuild
          subcommand: ${{ matrix.command }}
          scheme: swift-existential-container
          platform: ${{ matrix.platform }}
      - name: Release ${{ matrix.platform }}
        if: matrix.command != 'test'
        uses: capturecontext/swift-package-action@2.0
        with:
          workspace: Package.xcworkspace
          cache-derived-data: true
          command: xcodebuild
          subcommand: ${{ matrix.command }}
          scheme: swift-existential-container
          platform: ${{ matrix.platform }}
          config: Release
